debug: false

# Input: kspace directory. .dat data. Mounted external SSD through WSL
ksp_in_dir: "/mnt/f/01_data/01_prostate_raw_kspace_umcg_p1"                   #fastmri1_ksp_fpath
# ksp_in_dir: "/mnt/d/01_data/01_prostate_raw_kspace_umcg_p2"                   #fastmri2_out_fpath

# Location where the converted dataset will be stored and additional files.
out_root: "/mnt/d/01_data/02_processed_pst_ksp_umcg_p2"

# Parameter maps for the Siemens To ISMRMRD converter.
mrd_xml: "custom_param_maps/IsmrmrdParameterMap_Siemens_DIAG_UMCG.xml"  # Needed for conversion from .dat to .mrd. ismrmrd_param_map_xml
mrd_xsl: "custom_param_maps/IsmrmrdParameterMap_Siemens_DIAG_UMCG.xsl"  # Needed for conversion from .dat to .mrd. ismrmrd_param_map_xsl

# ANONYMIZED DICOM DIR. Processed by the Datamanager C# program. Dicoms have been converted into anon dicoms. The root location.
anon_dcms_dir: "/mnt/d/01_data/02_processed_pst_ksp_umcg_p2/data/sectra_dynacad_exp_dcms_and_rois_pat1_136_anon_dcms"
# anon_dcms_dir: "/mnt/d/01_data/02_processed_pst_ksp_umcg_p2/data/sectra_dynacad_exp_dcms_and_rois_pat137_172_anon_dcms"

# NIFTI DIR. Processed by the Datamanager C# program. Dicoms have been converted into nifti's. The root location.
nifti_dir: "/mnt/d/01_data/02_processed_pst_ksp_umcg_p2/data/sectra_dynacad_exp_dcms_and_rois_pat1_136_niftis"
# nifti_dir: "/mnt/d/01_data/02_processed_pst_ksp_umcg_p2/data/sectra_dynacad_exp_dcms_and_rois_pat137_172_niftis"

# Database and transfer stuff
transfer_to_hpc:  true  # Transfer all relevant files to Habrok with scp
username :        "p290820"
hostname:         "interactive1.hb.hpc.rug.nl"
destination_path: "/scratch/p290820/datasets/003_umcg_pst_ksps/data"
sqlite_db_fpath:  "/mnt/d/01_data/02_processed_pst_ksp_umcg_p2/database/dbs/db_from_habrok_quintin/master_habrok_20231106.db"
tablename_ksp:    "kspace_dset_info"  #name of the table containing info which files have been converted to mrd and h5 and transfered.
tablename_dcm:    "dicom_headers_v1"


# only these sequential patient IDs are considered for conversion
seq_id_filter: 
  # - "0063"
  # - "0064"
  # - "0065"
  # - "0066"
  # - "0067"
  # - "0068"
  # - "0069"
  # - "0070"
  # - "0071"
  # - "0072"
  # - "0073"
  # - "0074"
  # - "0075"
  # - "0076"
  # - "0077"
  # - "0078"
  # - "0079"
  # - "0080"
  # - "0081"
  # - "0082"
  # - "0083"
  # - "0084"
  # - "0085"
  # - "0086"
  # - "0087"
  # - "0088"
  # - "0089"
  # - "0090"
  # - "0091"
  # - "0092"
  # - "0093"
  # - "0094"
  # - "0095"  
  # - "0096"
  # - "0097"
  # - "0098"
  # - "0099"
  # - "0100"
  # - "0101"
  # - "0102"
  # - "0103"
  # - "0104"
  # - "0105"
  # - "0106"
  # - "0107"
  # - "0108"
  # - "0109"
  # - "0110"
  # - "0111"
  # - "0112"
  # - "0113"
  # - "0114"
  # - "0115"
  # - "0116"
  # - "0117"
  # - "0118"
  # - "0119"
  # - "0120"
  # - "0121"
  # - "0122"
  # - "0123"
  # - "0124"
  # - "0125"
  # - "0126"
  # - "0127"
  # - "0128"
  - "0129"
  # - "0130"
  # - "0131"
  # - "0132"
  # - "0133"
  # - "0134"
  # - "0135"
  # - "0136"
  # - "0137"
  # - "0138"
  # - "0139"
  # - "0140"
  # - "0141"
  # - "0142"
  # - "0143"
  # - "0144"
  # - "0145"
  # - "0146"
  # - "0147"
  # - "0148"
  # - "0149"
  # - "0150"
  # - "0151"
  # - "0152"    # Found 2 T2 tra kspaces. which one to use? # resolved
  # - "0153"
  # - "0154"
  # - "0155"
  # - "0156"
  # - "0157"    # Found 2 T2 tra kspaces. which one to use? # resolved
  # - "0158"
  # - "0159"
  # - "0160"
  # - "0161"
  # - "0162"
  # - "0163"
  # - "0164"   # Found 2 T2 tra kspaces. which one to use? # resolved
  # - "0165"
  # - "0166"
  # - "0167"   # Found 2 T2 tra kspaces. which one to use? # resolved
  # - "0168"
  # - "0169"
  # - "0170"
  # - "0171"
  # - "0172"

# Kspace conversion settings from .mrd to .h5
do_rm_zero_pad: true          # Remove zero padding from the kspace data
do_norm_to_ref: true          # Normalize the kspace data to the reference NYU data
max_phase_crop: null          # Maximum phase crop. If null, no cropping is done. If not null, the kspace data is cropped to this size.
max_mag_ref:    0.010586672   # Entire NYU test and validation dataset # one patient: 0.006096669


# significant IDs
significant_ids:
  - "ANON5046358"
  - "ANON9616598"
  - "ANON2379607"
  - "ANON8290811"
  - "ANON1586301"
  - "ANON8890538"
  - "ANON7748752"
  - "ANON1102778"
  - "ANON4982869"
  - "ANON7362087"
  - "ANON3951049"
  - "ANON9844606"
  - "ANON9843837"
  - "ANON7657657"
  - "ANON1562419"
  - "ANON4277586"
  - "ANON6964611"
  - "ANON7992094"
  - "ANON3394777"
  - "ANON3620419"
  - "ANON9724912"
  - "ANON3397001"
  - "ANON7189994"
  - "ANON9141039"
  - "ANON7649583"
  - "ANON9728185"
  - "ANON3474225"
  - "ANON0282755"
  - "ANON0369080"
  - "ANON0604912"
  - "ANON2361146"
  - "ANON9423619"
  - "ANON7041133"
  - "ANON8232550"
  - "ANON2563804"
  - "ANON3613611"
  - "ANON6365688"
  - "ANON9783006"
  - "ANON1327674"
  - "ANON9710044"
  - "ANON5517301"
  - "ANON2124757"
  - "ANON3357872"
  - "ANON1070291"
  - "ANON9719981"
  - "ANON7955208"
  - "ANON7642254"
  - "ANON0319974"
  - "ANON9972960"
  - "ANON0282398"
  - "ANON0913099"
  - "ANON7978458"
  - "ANON9840567"
  - "ANON5223499"
  - "ANON9806291"
  - "ANON5954143"
  - "ANON5895496"
  - "ANON3983890"
  - "ANON8634437"
  - "ANON6883869"
  - "ANON8828023"
  - "ANON4499321"
  - "ANON9763928"
  - "ANON9898497"
  - "ANON6073234"
  - "ANON4535412"
  - "ANON6141178"
  - "ANON8511628"
  - "ANON9534873"
  - "ANON9892116"
  - "ANON0891692"
  - "ANON9786899"
  - "ANON6365688"
  - "ANON9941969"
  - "ANON8024204"
  - "ANON9728761"
  - "ANON4189062"
  - "ANON5642073"
  - "ANON1562419"
  - "ANON8583296"
  - "ANON4035085"
  - "ANON7748630"
  - "ANON9883201"
  - "ANON0424679"
  - "ANON9816976"
  - "ANON8266491"
  - "ANON9310466"
  - "ANON3210850"
  - "ANON9665113"
  - "ANON0400743"
  - "ANON9223478"
  - "ANON3865800"
  - "ANON7141024"
  - "ANON7275574"
  - "ANON9629161"
  - "ANON7265874"
  - "ANON8610762"
  - "ANON0272089"
  - "ANON4747182"
  - "ANON8023509"
  - "ANON8627051"
  - "ANON5344332"
  - "ANON9879440"
  - "ANON8096961"
  - "ANON8035619"
  - "ANON1747790"
  - "ANON2666319"
  - "ANON0899488"
  - "ANON8018038"
  - "ANON7090827"
  - "ANON9752849"
  - "ANON2255419"
  - "ANON0335209"
  - "ANON7414571"
  - "ANON9604223"
  - "ANON4712664"
  - "ANON5824292"
  - "ANON4277586"
  - "ANON2411221"
  - "ANON5958718"